[[plugins]]#denite
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']

[[plugins]]#denite
repo = 'Shougo/neco-vim'
depends = ['deoplete.vim']

[[plugins]]#denite git source 
repo = 'chemzqm/vim-easygit'
depends = ['denite-git.vim']

[[plugins]]#denite
repo = 'chemzqm/denite-git'
depends = ['denite.vim']

[[plugins]]#typescript
repo = 'leafgarland/typescript-vim'

