[[plugins]]
repo = 'Shougo/unite.vim'
on_event = 'BufRead'
hook_add = '''
nnoremap [unite] <Nop>
nmap <C-u> [unite]
nmap <silent> [unite]<C-u> :<C-u>Unite filetype<CR>
nmap <silent> [unite]<C-p> :<C-u>Unite -default-action=tabopen file_rec<CR>
nmap <silent> [unite]<C-g> :<C-u>Unite -default-action=tabopen grep<CR>
nmap <silent> [unite]<C-u> :<C-u>Unite -default-action=tabopen file_mru file_rec<CR>
nmap <silent> [unite]<C-t> :<C-u>Unite tab<CR>
'''
