[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_event = 'BufRead'
hook_add = '''
nnoremap [denite] <Nop>
nmap <C-u> [denite]
nmap <silent> [denite]<C-g> :<C-u>Denite -default-action=tabopen -auto-highlight  grep<CR>
nmap <silent> [denite]<C-u> :<C-u>Denite -default-action=tabopen -auto-highlight  file_rec<CR>
nmap <silent> [denite]<C-r> :<C-u>Denite -default-action=tabopen -auto-highlight  file_mru<CR>
nmap <silent> [denite]<C-y> :<C-u>Denite -mode=normal  neoyank<CR>
nmap <silent> [denite]<C-t> :<C-u>Denite -mode=normal tab<CR>
'''

hook_post_source = '''
call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
'''
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'zchee/deoplete-go'
depends = ['deoplete.vim']

[[plugins]]#denite
repo = 'Shougo/neco-vim'
depends = ['deoplete.vim']


