[[plugins]]
repo = 'Shougo/unite.vim'
on_event = 'BufRead'
hook_add = '''
let g:unite_enable_start_insert = 1
let g:unite_enable_ignore_case = 1
let g:unite_enable_smart_case = 1

nnoremap [unite] <Nop>
nmap <C-u> [unite]
nmap <silent> [unite]<C-y> :<C-u>Unite filetype<CR>
nmap <silent> [unite]<C-p> :<C-u>Unite -default-action=tabopen file_rec/aync<CR>
nmap <silent> [unite]<C-g> :<C-u>Unite -default-action=tabopen grep<CR>
nmap <silent> [unite]<C-u> :<C-u>Unite -default-action=tabopen file_mru file_rec/async<CR>
nmap <silent> [unite]<C-t> :<C-u>Unite tab<CR>
'''
