[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
let g:unite_enable_start_insert = 1
let g:unite_enable_ignore_case = 1
let g:unite_enable_smart_case = 1
" let g:unite_source_file_mru_limit = 10
" let g:unite_source_directory_mru_limit = 10
let g:unite_split_rule = 'botright'

nnoremap [unite] <Nop>
nmap <C-u> [unite]
nmap <silent> [unite]<C-r> :<C-u>UniteResume -prompt-direction=below -auto-resize -silent grep-buffer<CR>
nmap <silent> [unite]<C-g> :<C-u>Unite -prompt-direction=below -auto-resize -start-insert grep:. -buffer-name=grep-buffer<CR>
" nmap <silent> [unite]<C-y> :<C-u>UniteResume search-buffer<CR>
" nmap <silent> [unite]<C-i> :<C-u>Unite -horizontal -start-insert <CR>
" nmap <silent> [unite]<C-u> :<C-u>Unite -horizontal -start-insert -buffer-name=search-buffer file_mru file_rec/git<CR>
" nmap <silent> [unite]<C-t> :<C-u>Unite -horizontal tab<CR>
'''
# [[plugins]]
# repo = 'Shougo/neoyank.vim'
